const t = {
	success: true,
	message: "GitHub repositories retrieved successfully.",
	data: [
		{
			githubRepoId: 1214353222,
			name: "pickaxe_and_shovel",
			fullName: "keithowino/pickaxe_and_shovel",
			description: "A creator's development portfolio.",
			githubUrl: "https://github.com/keithowino/pickaxe_and_shovel",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2026-09-22T14:14:00Z",
		},
		{
			githubRepoId: 1379815660,
			name: "context_editor",
			fullName: "keithowino/context_editor",
			description: "MCP project server.",
			githubUrl: "https://github.com/keithowino/context_editor",
			primaryLanguage: "Python",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2026-09-21T16:16:28Z",
		},
		{
			githubRepoId: 1378899224,
			name: "mcp_fastmcp_course",
			fullName: "keithowino/mcp_fastmcp_course",
			description: "FastMCP Training Wheels.",
			githubUrl: "https://github.com/keithowino/mcp_fastmcp_course",
			primaryLanguage: "Python",
			topics: ["agentic-programming", "ai", "llms", "mcp"],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2026-09-21T10:33:01Z",
		},
		{
			githubRepoId: 1281115050,
			name: "tassiaqca",
			fullName: "keithowino/tassiaqca",
			description:
				"Quiet Compound Assets — Community-centric e-commerce operating system connecting customers, businesses, and communities.",
			githubUrl: "https://github.com/keithowino/tassiaqca",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2026-09-15T09:55:52Z",
		},
		{
			githubRepoId: 1280619313,
			name: "mern_template",
			fullName: "keithowino/mern_template",
			description: null,
			githubUrl: "https://github.com/keithowino/mern_template",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2026-06-25T19:13:58Z",
		},
		{
			githubRepoId: 1238530787,
			name: "r4-hub",
			fullName: "keithowino/r4-hub",
			description:
				"All your developer resources. Organized. Accessible. Powered by AI.",
			githubUrl: "https://github.com/keithowino/r4-hub",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2026-06-25T15:04:32Z",
		},
		{
			githubRepoId: 1277287457,
			name: "self_healing_ci-cd_pipeline",
			fullName: "keithowino/self_healing_ci-cd_pipeline",
			description: null,
			githubUrl:
				"https://github.com/keithowino/self_healing_ci-cd_pipeline",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2026-06-22T18:57:52Z",
		},
		{
			githubRepoId: 1266232765,
			name: "momma_nuts_colab",
			fullName: "keithowino/momma_nuts_colab",
			description: null,
			githubUrl: "https://github.com/keithowino/momma_nuts_colab",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2026-06-14T16:04:23Z",
		},
		{
			githubRepoId: 1251089308,
			name: "daraja-intro",
			fullName: "keithowino/daraja-intro",
			description: "Daraja 3.0 integration walkthrough.",
			githubUrl: "https://github.com/keithowino/daraja-intro",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2026-05-27T13:38:58Z",
		},
		{
			githubRepoId: 1248272122,
			name: "tassia-connect-clone",
			fullName: "keithowino/tassia-connect-clone",
			description: null,
			githubUrl: "https://github.com/keithowino/tassia-connect-clone",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2026-05-24T12:42:07Z",
		},
		{
			githubRepoId: 1235268897,
			name: "preemie",
			fullName: "keithowino/preemie",
			description: null,
			githubUrl: "https://github.com/keithowino/preemie",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2026-05-11T07:09:12Z",
		},
		{
			githubRepoId: 1226492875,
			name: "reactCrud",
			fullName: "keithowino/reactCrud",
			description: null,
			githubUrl: "https://github.com/keithowino/reactCrud",
			primaryLanguage: "TypeScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2026-05-01T14:07:03Z",
		},
		{
			githubRepoId: 1224777373,
			name: "instantChat",
			fullName: "keithowino/instantChat",
			description:
				"A real-time chat application built with React (Vite), Tailwind CSS, and Firebase",
			githubUrl: "https://github.com/keithowino/instantChat",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2026-04-29T20:57:57Z",
		},
		{
			githubRepoId: 1221511207,
			name: "online-job-portal",
			fullName: "keithowino/online-job-portal",
			description: null,
			githubUrl: "https://github.com/keithowino/online-job-portal",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2026-04-27T09:01:01Z",
		},
		{
			githubRepoId: 1220055778,
			name: "image-pro",
			fullName: "keithowino/image-pro",
			description: "Tutorial follow-up build",
			githubUrl: "https://github.com/keithowino/image-pro",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2026-04-25T14:42:08Z",
		},
		{
			githubRepoId: 1218946541,
			name: "codemylife",
			fullName: "keithowino/codemylife",
			description: "Firebase tutorial followup",
			githubUrl: "https://github.com/keithowino/codemylife",
			primaryLanguage: "HTML",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2026-04-23T17:25:14Z",
		},
		{
			githubRepoId: 1215936779,
			name: "kanban_board",
			fullName: "keithowino/kanban_board",
			description: "Progress tracker",
			githubUrl: "https://github.com/keithowino/kanban_board",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2026-04-21T16:13:18Z",
		},
		{
			githubRepoId: 1138188896,
			name: "bait-fusion",
			fullName: "keithowino/bait-fusion",
			description: "A course sharing site.",
			githubUrl: "https://github.com/keithowino/bait-fusion",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2026-04-19T08:20:48Z",
		},
		{
			githubRepoId: 1138287765,
			name: "bait-fusion-google-ai-studio-gen",
			fullName: "keithowino/bait-fusion-google-ai-studio-gen",
			description: "Course sharing site",
			githubUrl:
				"https://github.com/keithowino/bait-fusion-google-ai-studio-gen",
			primaryLanguage: "TypeScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2026-04-19T08:19:37Z",
		},
		{
			githubRepoId: 1140787984,
			name: "bait-fusion-version-2",
			fullName: "keithowino/bait-fusion-version-2",
			description: "A course sharing site.",
			githubUrl: "https://github.com/keithowino/bait-fusion-version-2",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2026-04-19T08:16:53Z",
		},
		{
			githubRepoId: 1213931464,
			name: "pickaxe_and_shovel_bolt_gen_v1",
			fullName: "keithowino/pickaxe_and_shovel_bolt_gen_v1",
			description: null,
			githubUrl:
				"https://github.com/keithowino/pickaxe_and_shovel_bolt_gen_v1",
			primaryLanguage: "TypeScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: true,
			defaultBranch: "main",
			updatedAt: "2026-04-18T01:02:17Z",
		},
		{
			githubRepoId: 1211366682,
			name: "tassia_conect_v5_bolt_gen",
			fullName: "keithowino/tassia_conect_v5_bolt_gen",
			description: "Hyperlocal platform",
			githubUrl:
				"https://github.com/keithowino/tassia_conect_v5_bolt_gen",
			primaryLanguage: "TypeScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: true,
			defaultBranch: "main",
			updatedAt: "2026-04-17T22:57:04Z",
		},
		{
			githubRepoId: 1213339009,
			name: "tassiaconnect",
			fullName: "keithowino/tassiaconnect",
			description:
				"This platform is a hyperlocal marketplace and service discovery platform focused on Tassia Complex, Embakasi East, Nairobi, Kenya.",
			githubUrl: "https://github.com/keithowino/tassiaconnect",
			primaryLanguage: "TypeScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: true,
			defaultBranch: "main",
			updatedAt: "2026-04-17T11:13:01Z",
		},
		{
			githubRepoId: 1210916333,
			name: "tassia-business-connect",
			fullName: "keithowino/tassia-business-connect",
			description: null,
			githubUrl: "https://github.com/keithowino/tassia-business-connect",
			primaryLanguage: "TypeScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: true,
			defaultBranch: "main",
			updatedAt: "2026-04-15T02:18:23Z",
		},
		{
			githubRepoId: 1210945263,
			name: "tassia_connect_v3",
			fullName: "keithowino/tassia_connect_v3",
			description: "Exploit Nairobi tour",
			githubUrl: "https://github.com/keithowino/tassia_connect_v3",
			primaryLanguage: "TypeScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: true,
			defaultBranch: "main",
			updatedAt: "2026-04-15T01:42:28Z",
		},
		{
			githubRepoId: 1210930441,
			name: "tassia_ledger",
			fullName: "keithowino/tassia_ledger",
			description: "Exploit Nairobi tour",
			githubUrl: "https://github.com/keithowino/tassia_ledger",
			primaryLanguage: "TypeScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: true,
			defaultBranch: "main",
			updatedAt: "2026-04-14T22:46:19Z",
		},
		{
			githubRepoId: 1176625093,
			name: "simple_crud_api",
			fullName: "keithowino/simple_crud_api",
			description: "A crud api tutorial",
			githubUrl: "https://github.com/keithowino/simple_crud_api",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2026-03-09T08:03:28Z",
		},
		{
			githubRepoId: 1122290897,
			name: "film-moment-tracker",
			fullName: "keithowino/film-moment-tracker",
			description: "Keeps a tracks of the films i have watched.",
			githubUrl: "https://github.com/keithowino/film-moment-tracker",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2025-12-27T19:56:47Z",
		},
		{
			githubRepoId: 1091771503,
			name: "software-development",
			fullName: "keithowino/software-development",
			description: null,
			githubUrl: "https://github.com/keithowino/software-development",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2025-11-07T13:55:52Z",
		},
		{
			githubRepoId: 798752438,
			name: "react-hooks-information-flow-lab",
			fullName: "keithowino/react-hooks-information-flow-lab",
			description: null,
			githubUrl:
				"https://github.com/keithowino/react-hooks-information-flow-lab",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-05-10T11:53:24Z",
		},
		{
			githubRepoId: 798637625,
			name: "react-hooks-state-and-events-lab",
			fullName: "keithowino/react-hooks-state-and-events-lab",
			description: null,
			githubUrl:
				"https://github.com/keithowino/react-hooks-state-and-events-lab",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-05-10T10:55:45Z",
		},
		{
			githubRepoId: 795971402,
			name: "react-hooks-state-arrays",
			fullName: "keithowino/react-hooks-state-arrays",
			description: null,
			githubUrl: "https://github.com/keithowino/react-hooks-state-arrays",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-05-10T07:14:47Z",
		},
		{
			githubRepoId: 795848026,
			name: "react-hooks-state-and-events-codealong",
			fullName: "keithowino/react-hooks-state-and-events-codealong",
			description: null,
			githubUrl:
				"https://github.com/keithowino/react-hooks-state-and-events-codealong",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-05-04T08:26:20Z",
		},
		{
			githubRepoId: 795711427,
			name: "react-hooks-state",
			fullName: "keithowino/react-hooks-state",
			description: null,
			githubUrl: "https://github.com/keithowino/react-hooks-state",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-05-03T21:41:08Z",
		},
		{
			githubRepoId: 795454353,
			name: "react-hooks-event-handling-lab",
			fullName: "keithowino/react-hooks-event-handling-lab",
			description: null,
			githubUrl:
				"https://github.com/keithowino/react-hooks-event-handling-lab",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-05-03T21:37:25Z",
		},
		{
			githubRepoId: 793812684,
			name: "react-hooks-component-props-mini-project",
			fullName: "keithowino/react-hooks-component-props-mini-project",
			description: null,
			githubUrl:
				"https://github.com/keithowino/react-hooks-component-props-mini-project",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 1,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-04-30T05:28:22Z",
		},
		{
			githubRepoId: 793471716,
			name: "react-hooks-lists-and-keys-lab",
			fullName: "keithowino/react-hooks-lists-and-keys-lab",
			description: null,
			githubUrl:
				"https://github.com/keithowino/react-hooks-lists-and-keys-lab",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-04-29T22:53:05Z",
		},
		{
			githubRepoId: 793173688,
			name: "react-hooks-props-basics-lab",
			fullName: "keithowino/react-hooks-props-basics-lab",
			description: null,
			githubUrl:
				"https://github.com/keithowino/react-hooks-props-basics-lab",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-04-29T09:07:07Z",
		},
		{
			githubRepoId: 793057748,
			name: "react-hooks-import-export-lab",
			fullName: "keithowino/react-hooks-import-export-lab",
			description: null,
			githubUrl:
				"https://github.com/keithowino/react-hooks-import-export-lab",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-04-28T11:02:24Z",
		},
		{
			githubRepoId: 793013109,
			name: "react-hooks-components-basics-lab",
			fullName: "keithowino/react-hooks-components-basics-lab",
			description: null,
			githubUrl:
				"https://github.com/keithowino/react-hooks-components-basics-lab",
			primaryLanguage: "HTML",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2024-04-28T08:07:36Z",
		},
		{
			githubRepoId: 793026369,
			name: "react-hooks-import-export",
			fullName: "keithowino/react-hooks-import-export",
			description: null,
			githubUrl:
				"https://github.com/keithowino/react-hooks-import-export",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-04-28T08:06:08Z",
		},
		{
			githubRepoId: 792725807,
			name: "react-hooks-components-basics",
			fullName: "keithowino/react-hooks-components-basics",
			description: null,
			githubUrl:
				"https://github.com/keithowino/react-hooks-components-basics",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-04-27T11:56:26Z",
		},
		{
			githubRepoId: 792718393,
			name: "react-hooks-lecture-videos-components-and-props",
			fullName:
				"keithowino/react-hooks-lecture-videos-components-and-props",
			description: null,
			githubUrl:
				"https://github.com/keithowino/react-hooks-lecture-videos-components-and-props",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2024-04-27T11:27:41Z",
		},
		{
			githubRepoId: 792072256,
			name: "react-hooks-react-app-example",
			fullName: "keithowino/react-hooks-react-app-example",
			description: null,
			githubUrl:
				"https://github.com/keithowino/react-hooks-react-app-example",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-04-25T23:26:27Z",
		},
		{
			githubRepoId: 791363744,
			name: "react-hooks-running-tests",
			fullName: "keithowino/react-hooks-running-tests",
			description: null,
			githubUrl:
				"https://github.com/keithowino/react-hooks-running-tests",
			primaryLanguage: "HTML",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2024-04-25T23:26:09Z",
		},
		{
			githubRepoId: 792062118,
			name: "react-hooks-intro-to-npm-readme",
			fullName: "keithowino/react-hooks-intro-to-npm-readme",
			description: null,
			githubUrl:
				"https://github.com/keithowino/react-hooks-intro-to-npm-readme",
			primaryLanguage: "HTML",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2024-04-25T23:25:16Z",
		},
		{
			githubRepoId: 784923247,
			name: "the-collector",
			fullName: "keithowino/the-collector",
			description: null,
			githubUrl: "https://github.com/keithowino/the-collector",
			primaryLanguage: "JavaScript",
			topics: ["api", "dom-manipulation"],
			stars: 0,
			forks: 1,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2024-04-13T08:28:43Z",
		},
		{
			githubRepoId: 783582845,
			name: "Code-challenge-3",
			fullName: "keithowino/Code-challenge-3",
			description: null,
			githubUrl: "https://github.com/keithowino/Code-challenge-3",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2024-04-08T07:20:34Z",
		},
		{
			githubRepoId: 782803611,
			name: "sa-03-w03-code-challenge",
			fullName: "keithowino/sa-03-w03-code-challenge",
			description: null,
			githubUrl: "https://github.com/keithowino/sa-03-w03-code-challenge",
			primaryLanguage: "JavaScript",
			topics: ["api-server", "dom-manipulation", "event-handling"],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2024-04-08T06:46:16Z",
		},
		{
			githubRepoId: 783431688,
			name: "phase-1-algorithms-palindrome",
			fullName: "keithowino/phase-1-algorithms-palindrome",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-algorithms-palindrome",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2024-04-07T21:25:04Z",
		},
		{
			githubRepoId: 783430602,
			name: "phase-1-algorithms-intro-to-algorithmic-problem-solving",
			fullName:
				"keithowino/phase-1-algorithms-intro-to-algorithmic-problem-solving",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-algorithms-intro-to-algorithmic-problem-solving",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2024-04-07T21:20:46Z",
		},
		{
			githubRepoId: 783429315,
			name: "phase-1-javascript-quotes-practice",
			fullName: "keithowino/phase-1-javascript-quotes-practice",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-javascript-quotes-practice",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-04-07T21:15:36Z",
		},
		{
			githubRepoId: 783429019,
			name: "phase-1-bookliker",
			fullName: "keithowino/phase-1-bookliker",
			description: null,
			githubUrl: "https://github.com/keithowino/phase-1-bookliker",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-04-07T21:14:35Z",
		},
		{
			githubRepoId: 783428641,
			name: "phase-1-practice-dog-show",
			fullName: "keithowino/phase-1-practice-dog-show",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-practice-dog-show",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-04-07T21:13:07Z",
		},
		{
			githubRepoId: 783428142,
			name: "phase-1-woof-woof-js-practice",
			fullName: "keithowino/phase-1-woof-woof-js-practice",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-woof-woof-js-practice",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-04-07T21:11:18Z",
		},
		{
			githubRepoId: 783426662,
			name: "phase-1-monsters",
			fullName: "keithowino/phase-1-monsters",
			description: null,
			githubUrl: "https://github.com/keithowino/phase-1-monsters",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-04-07T21:06:39Z",
		},
		{
			githubRepoId: 783426274,
			name: "phase-1-github-search-app",
			fullName: "keithowino/phase-1-github-search-app",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-github-search-app",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-04-07T21:05:18Z",
		},
		{
			githubRepoId: 783425881,
			name: "phase-1-practice-toy-tale",
			fullName: "keithowino/phase-1-practice-toy-tale",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-practice-toy-tale",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-04-07T21:03:50Z",
		},
		{
			githubRepoId: 783286004,
			name: "phase-1-practice-dog-ceo",
			fullName: "keithowino/phase-1-practice-dog-ceo",
			description: null,
			githubUrl: "https://github.com/keithowino/phase-1-practice-dog-ceo",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-04-07T21:00:07Z",
		},
		{
			githubRepoId: 782918201,
			name: "phase-1-practice-interacting-with-the-dom",
			fullName: "keithowino/phase-1-practice-interacting-with-the-dom",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-practice-interacting-with-the-dom",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-04-07T09:36:09Z",
		},
		{
			githubRepoId: 782468740,
			name: "phase-1-building-simple-liker",
			fullName: "keithowino/phase-1-building-simple-liker",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-building-simple-liker",
			primaryLanguage: "JavaScript",
			topics: ["dom-manipulation", "fetch-api"],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-04-06T12:11:24Z",
		},
		{
			githubRepoId: 781367633,
			name: "phase-1-sending-data-with-fetch",
			fullName: "keithowino/phase-1-sending-data-with-fetch",
			description: "Understanding post method in API.",
			githubUrl:
				"https://github.com/keithowino/phase-1-sending-data-with-fetch",
			primaryLanguage: "JavaScript",
			topics: ["dom-manipulation", "fetch-api", "post"],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-04-04T16:37:11Z",
		},
		{
			githubRepoId: 781364371,
			name: "phase-1-lecture-videos-delete-requests",
			fullName: "keithowino/phase-1-lecture-videos-delete-requests",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-lecture-videos-delete-requests",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2024-04-03T08:39:39Z",
		},
		{
			githubRepoId: 781360499,
			name: "phase-1-lecture-videos-patch-requests",
			fullName: "keithowino/phase-1-lecture-videos-patch-requests",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-lecture-videos-patch-requests",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2024-04-03T08:30:29Z",
		},
		{
			githubRepoId: 781295966,
			name: "phase-1-lecture-videos-post-requests",
			fullName: "keithowino/phase-1-lecture-videos-post-requests",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-lecture-videos-post-requests",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2024-04-03T05:42:56Z",
		},
		{
			githubRepoId: 781290565,
			name: "phase-1-asynchronous-javascript",
			fullName: "keithowino/phase-1-asynchronous-javascript",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-asynchronous-javascript",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-04-03T05:25:12Z",
		},
		{
			githubRepoId: 780668183,
			name: "phase-1-js-fetch-on-demand-with-forms",
			fullName: "keithowino/phase-1-js-fetch-on-demand-with-forms",
			description: "Understanding fetch API.",
			githubUrl:
				"https://github.com/keithowino/phase-1-js-fetch-on-demand-with-forms",
			primaryLanguage: "JavaScript",
			topics: ["dom-manipulation", "fetch-api"],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2024-04-02T03:11:39Z",
		},
		{
			githubRepoId: 780646775,
			name: "phase-1-fetch-lab",
			fullName: "keithowino/phase-1-fetch-lab",
			description: null,
			githubUrl: "https://github.com/keithowino/phase-1-fetch-lab",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-04-01T23:44:08Z",
		},
		{
			githubRepoId: 780643220,
			name: "phase-1-using-fetch",
			fullName: "keithowino/phase-1-using-fetch",
			description: null,
			githubUrl: "https://github.com/keithowino/phase-1-using-fetch",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-04-01T22:22:15Z",
		},
		{
			githubRepoId: 780636623,
			name: "phase-1-lecture-videos-get-requests",
			fullName: "keithowino/phase-1-lecture-videos-get-requests",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-lecture-videos-get-requests",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2024-04-01T21:59:51Z",
		},
		{
			githubRepoId: 780620932,
			name: "phase-1-lecture-videos-asynchronous-javascript-and-fetch",
			fullName:
				"keithowino/phase-1-lecture-videos-asynchronous-javascript-and-fetch",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-lecture-videos-asynchronous-javascript-and-fetch",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2024-04-01T21:08:40Z",
		},
		{
			githubRepoId: 780501810,
			name: "phase-1-using-json-server-and-postman",
			fullName: "keithowino/phase-1-using-json-server-and-postman",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-using-json-server-and-postman",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2024-04-01T17:15:11Z",
		},
		{
			githubRepoId: 780320069,
			name: "phase-1-lecture-videos-postman",
			fullName: "keithowino/phase-1-lecture-videos-postman",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-lecture-videos-postman",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2024-04-01T08:09:19Z",
		},
		{
			githubRepoId: 780315286,
			name: "phase-1-lecture-videos-json",
			fullName: "keithowino/phase-1-lecture-videos-json",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-lecture-videos-json",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2024-04-01T07:54:13Z",
		},
		{
			githubRepoId: 779566385,
			name: "sa-02-w02-code-challenge",
			fullName: "keithowino/sa-02-w02-code-challenge",
			description: null,
			githubUrl: "https://github.com/keithowino/sa-02-w02-code-challenge",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2024-03-30T07:52:21Z",
		},
		{
			githubRepoId: 779325738,
			name: "phase-1-tasklister-mini-project",
			fullName: "keithowino/phase-1-tasklister-mini-project",
			description: "The scripting of a to do list program.",
			githubUrl:
				"https://github.com/keithowino/phase-1-tasklister-mini-project",
			primaryLanguage: "HTML",
			topics: ["dom-manipulation", "forms", "functions"],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-03-30T06:34:33Z",
		},
		{
			githubRepoId: 779307907,
			name: "phase-1-domcontentloaded",
			fullName: "keithowino/phase-1-domcontentloaded",
			description: null,
			githubUrl: "https://github.com/keithowino/phase-1-domcontentloaded",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-03-29T15:11:00Z",
		},
		{
			githubRepoId: 779305245,
			name: "phase-1-lecture-videos-forms",
			fullName: "keithowino/phase-1-lecture-videos-forms",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-lecture-videos-forms",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2024-03-29T14:21:47Z",
		},
		{
			githubRepoId: 779228965,
			name: "phase-0-javascript-events-acting-on-events-lab",
			fullName:
				"keithowino/phase-0-javascript-events-acting-on-events-lab",
			description: "Playing with the DOM.",
			githubUrl:
				"https://github.com/keithowino/phase-0-javascript-events-acting-on-events-lab",
			primaryLanguage: "JavaScript",
			topics: ["dom-manipulation", "events", "javascript-interaction"],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-03-29T14:01:25Z",
		},
		{
			githubRepoId: 779203122,
			name: "phase-0-javascript-events-event-listening-lab",
			fullName:
				"keithowino/phase-0-javascript-events-event-listening-lab",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-0-javascript-events-event-listening-lab",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-03-29T10:17:17Z",
		},
		{
			githubRepoId: 779100533,
			name: "phase-1-stitching-together-the-three-pillars",
			fullName: "keithowino/phase-1-stitching-together-the-three-pillars",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-stitching-together-the-three-pillars",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-03-29T05:17:56Z",
		},
		{
			githubRepoId: 778634120,
			name: "phase-1-advanced-function-parameter-syntax-default-rest-spread",
			fullName:
				"keithowino/phase-1-advanced-function-parameter-syntax-default-rest-spread",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-advanced-function-parameter-syntax-default-rest-spread",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-03-28T05:02:47Z",
		},
		{
			githubRepoId: 778613790,
			name: "phase-1-destructuring-assignment",
			fullName: "keithowino/phase-1-destructuring-assignment",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-destructuring-assignment",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-03-28T04:46:33Z",
		},
		{
			githubRepoId: 778542251,
			name: "phase-1-arrays-objects-what-is-really-going-on",
			fullName:
				"keithowino/phase-1-arrays-objects-what-is-really-going-on",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-arrays-objects-what-is-really-going-on",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2024-03-27T23:06:00Z",
		},
		{
			githubRepoId: 778519533,
			name: "phase-1-using-array-reduce",
			fullName: "keithowino/phase-1-using-array-reduce",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-using-array-reduce",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-03-27T22:41:29Z",
		},
		{
			githubRepoId: 778470153,
			name: "phase-1-array-map-method-lab",
			fullName: "keithowino/phase-1-array-map-method-lab",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-array-map-method-lab",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-03-27T21:16:47Z",
		},
		{
			githubRepoId: 778108926,
			name: "phase-1-array-filter-method-lab",
			fullName: "keithowino/phase-1-array-filter-method-lab",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-array-filter-method-lab",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-03-27T17:01:28Z",
		},
		{
			githubRepoId: 777944074,
			name: "keithowino",
			fullName: "keithowino/keithowino",
			description: "Github profile.",
			githubUrl: "https://github.com/keithowino/keithowino",
			primaryLanguage: null,
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2024-03-26T19:43:58Z",
		},
		{
			githubRepoId: 777706433,
			name: "phase-1-array-find-method-lab",
			fullName: "keithowino/phase-1-array-find-method-lab",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-array-find-method-lab",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-03-26T19:22:41Z",
		},
		{
			githubRepoId: 775802408,
			name: "phase-1-object-ball",
			fullName: "keithowino/phase-1-object-ball",
			description: null,
			githubUrl: "https://github.com/keithowino/phase-1-object-ball",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2024-03-25T07:42:00Z",
		},
		{
			githubRepoId: 776304729,
			name: "sa-01-w1-code-challenge",
			fullName: "keithowino/sa-01-w1-code-challenge",
			description: "This is a code challenge.",
			githubUrl: "https://github.com/keithowino/sa-01-w1-code-challenge",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "main",
			updatedAt: "2024-03-23T11:20:03Z",
		},
		{
			githubRepoId: 775610598,
			name: "phase-1-lexical-scoping-readme",
			fullName: "keithowino/phase-1-lexical-scoping-readme",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-lexical-scoping-readme",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-03-21T18:48:23Z",
		},
		{
			githubRepoId: 775440616,
			name: "phase-1-scope-lab",
			fullName: "keithowino/phase-1-scope-lab",
			description: null,
			githubUrl: "https://github.com/keithowino/phase-1-scope-lab",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-03-21T17:30:50Z",
		},
		{
			githubRepoId: 775355952,
			name: "phase-1-first-class-functions-lab",
			fullName: "keithowino/phase-1-first-class-functions-lab",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-first-class-functions-lab",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-03-21T10:42:53Z",
		},
		{
			githubRepoId: 775259363,
			name: "phase-1-first-class-functions",
			fullName: "keithowino/phase-1-first-class-functions",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-first-class-functions",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-03-21T04:24:34Z",
		},
		{
			githubRepoId: 775244524,
			name: "phase-1-arrow-functions",
			fullName: "keithowino/phase-1-arrow-functions",
			description: null,
			githubUrl: "https://github.com/keithowino/phase-1-arrow-functions",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-03-21T03:16:28Z",
		},
		{
			githubRepoId: 774917293,
			name: "phase-1-javascript-functions-continued",
			fullName: "keithowino/phase-1-javascript-functions-continued",
			description: null,
			githubUrl:
				"https://github.com/keithowino/phase-1-javascript-functions-continued",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-03-20T16:31:51Z",
		},
		{
			githubRepoId: 774350775,
			name: "phase-1-functions-lab",
			fullName: "keithowino/phase-1-functions-lab",
			description: null,
			githubUrl: "https://github.com/keithowino/phase-1-functions-lab",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-03-20T11:55:43Z",
		},
		{
			githubRepoId: 774292938,
			name: "phase-1-arithmetic-lab",
			fullName: "keithowino/phase-1-arithmetic-lab",
			description: null,
			githubUrl: "https://github.com/keithowino/phase-1-arithmetic-lab",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-03-19T10:47:18Z",
		},
		{
			githubRepoId: 774251147,
			name: "phase-1-control-flow-lab",
			fullName: "keithowino/phase-1-control-flow-lab",
			description: null,
			githubUrl: "https://github.com/keithowino/phase-1-control-flow-lab",
			primaryLanguage: "JavaScript",
			topics: [],
			stars: 0,
			forks: 0,
			isPrivate: false,
			defaultBranch: "master",
			updatedAt: "2024-03-19T09:35:51Z",
		},
	],
};
