@baseUrl = http://localhost:5000/api/v1
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWI2ZGZkMDA1YzkxZGEzYTg3Y2ZkMjMiLCJlbWFpbCI6ImRlc2lnbnNvbHV0aW9uc0BnbWFpbC5jb20iLCJzaWQiOiI2YWI4YjFjZTNmZWYzODk3MDFmMjc4NGMiLCJpYXQiOjE3OTA0ODkwMzgsImV4cCI6MTc5MDU3NTQzOCwiYXVkIjoicGlja2F4ZS1hbmQtc2hvdmVsLWNsaWVudCIsImlzcyI6InBpY2theGUtYW5kLXNob3ZlbCJ9.XIl0icWs9T8JT8WDveaR0CMzHZ7eiycM3F0Wgm1E7Hg
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWI2ZGZkMDA1YzkxZGEzYTg3Y2ZkMjQiLCJlbWFpbCI6InJlbWJvMTIzNEBnbWFpbC5jb20iLCJzaWQiOiI2YWI4YjE1MzNmZWYzODk3MDFmMjc4NGIiLCJpYXQiOjE3OTA0ODg5MTUsImV4cCI6MTc5MDU3NTMxNSwiYXVkIjoicGlja2F4ZS1hbmQtc2hvdmVsLWNsaWVudCIsImlzcyI6InBpY2theGUtYW5kLXNob3ZlbCJ9.dM_nBzQ1LUNb92PCD_Rn4c0rtlNoyU4VUJQJbxOFjoY

@projectIdA = 6ab8b4023fef389701f27851
@projectIdB = 6ab8b40f3fef389701f27852
@projectIdC = 6ab8b41b3fef389701f27853
@projectIdD = 6ab8bdcc1f2f83c21fd6fd8e

### Test 1: Successfully reorder projects
PATCH {{baseUrl}}/projects/admin/order
Content-Type: application/json
Cookie: accessToken={{adminToken}}

{
  "orderedProjectIds": [
    "{{projectIdB}}", 
    "{{projectIdD}}", 
    "{{projectIdA}}", 
    "{{projectIdC}}"
  ]
}